#include "BlueprintLLMModule.h"
#include "CommandServer.h"
#include "DSLImporter.h"
#include "BlueprintBuilder.h"

#include "ToolMenus.h"
#include "DesktopPlatformModule.h"
#include "IDesktopPlatform.h"
#include "Framework/Application/SlateApplication.h"
#include "Misc/MessageDialog.h"

#define LOCTEXT_NAMESPACE "FBlueprintLLMModule"

void FBlueprintLLMModule::StartupModule()
{
	UToolMenus::RegisterStartupCallback(
		FSimpleMulticastDelegate::FDelegate::CreateRaw(this, &FBlueprintLLMModule::RegisterMenus));

	// Auto-start the command server
	CommandServer = MakeUnique<FCommandServer>();
	if (!CommandServer->Start())
	{
		UE_LOG(LogBlueprintLLM, Warning, TEXT("Command server failed to start on plugin load"));
	}
}

void FBlueprintLLMModule::ShutdownModule()
{
	if (CommandServer)
	{
		CommandServer->Stop();
		CommandServer.Reset();
	}

	UToolMenus::UnRegisterStartupCallback(this);
	UToolMenus::UnregisterOwner(this);
}

void FBlueprintLLMModule::RegisterMenus()
{
	FToolMenuOwnerScoped OwnerScoped(this);

	// Add to Tools menu
	UToolMenu* ToolsMenu = UToolMenus::Get()->ExtendMenu("LevelEditor.MainMenu.Tools");
	FToolMenuSection& Section = ToolsMenu->FindOrAddSection("BlueprintLLM");
	Section.Label = LOCTEXT("BlueprintLLMSection", "BlueprintLLM");

	Section.AddMenuEntry(
		"ImportDSL",
		LOCTEXT("ImportDSLLabel", "Import DSL Blueprint..."),
		LOCTEXT("ImportDSLTooltip", "Import a .blueprint.json file generated by the BlueprintLLM DSL parser"),
		FSlateIcon(),
		FUIAction(FExecuteAction::CreateRaw(this, &FBlueprintLLMModule::OnImportDSLClicked))
	);

	Section.AddMenuEntry(
		"ToggleCommandServer",
		LOCTEXT("ToggleServerLabel", "Toggle Command Server"),
		LOCTEXT("ToggleServerTooltip", "Start/stop the TCP command server on port 13377"),
		FSlateIcon(),
		FUIAction(
			FExecuteAction::CreateRaw(this, &FBlueprintLLMModule::OnToggleCommandServer),
			FCanExecuteAction(),
			FIsActionChecked::CreateRaw(this, &FBlueprintLLMModule::IsCommandServerRunning)),
		EUserInterfaceActionType::ToggleButton
	);
}

void FBlueprintLLMModule::OnImportDSLClicked()
{
	// Open file dialog
	IDesktopPlatform* DesktopPlatform = FDesktopPlatformModule::Get();
	if (!DesktopPlatform)
	{
		return;
	}

	TArray<FString> OutFiles;
	const bool bOpened = DesktopPlatform->OpenFileDialog(
		FSlateApplication::Get().FindBestParentWindowHandleForDialogs(nullptr),
		TEXT("Select Blueprint JSON IR"),
		FPaths::ProjectContentDir(),
		TEXT(""),
		TEXT("Blueprint JSON (*.blueprint.json)|*.blueprint.json|JSON Files (*.json)|*.json"),
		EFileDialogFlags::None,
		OutFiles
	);

	if (!bOpened || OutFiles.Num() == 0)
	{
		return;
	}

	const FString& JsonPath = OutFiles[0];

	// Parse IR
	FDSLBlueprint DSL;
	if (!FDSLImporter::ParseIR(JsonPath, DSL))
	{
		FMessageDialog::Open(EAppMsgType::Ok,
			FText::Format(LOCTEXT("ParseError", "Failed to parse: {0}"), FText::FromString(JsonPath)));
		return;
	}

	// Build Blueprint
	const FString PackagePath = TEXT("/Game/BlueprintLLM/Generated");
	UBlueprint* NewBP = FBlueprintBuilder::CreateBlueprint(DSL, PackagePath);

	if (NewBP)
	{
		FMessageDialog::Open(EAppMsgType::Ok,
			FText::Format(LOCTEXT("ImportSuccess", "Created Blueprint: {0}\nNodes: {1}, Connections: {2}"),
				FText::FromString(DSL.Name),
				FText::AsNumber(DSL.Nodes.Num()),
				FText::AsNumber(DSL.Connections.Num())));
	}
	else
	{
		FMessageDialog::Open(EAppMsgType::Ok,
			LOCTEXT("BuildError", "Failed to build Blueprint from IR. Check Output Log for details."));
	}
}

void FBlueprintLLMModule::OnToggleCommandServer()
{
	if (!CommandServer)
	{
		CommandServer = MakeUnique<FCommandServer>();
	}

	if (CommandServer->IsRunning())
	{
		CommandServer->Stop();
		UE_LOG(LogBlueprintLLM, Log, TEXT("Command server stopped via menu"));
	}
	else
	{
		if (CommandServer->Start())
		{
			UE_LOG(LogBlueprintLLM, Log, TEXT("Command server started via menu"));
		}
	}
}

bool FBlueprintLLMModule::IsCommandServerRunning() const
{
	return CommandServer && CommandServer->IsRunning();
}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FBlueprintLLMModule, BlueprintLLM)
